// PROGRAMA C03EX4A.CPP

/* ler uma temperatura em graus Celsius e apresentá-la convertida em graus Fahrenheit.
A fórmula de conversao é F = C * 9 / 5 + 32, sendo F a temperatura em Fahrenheit e C a temperatura em Celsius.*/

#include <iostream>
#include <cstdint>

using namespace std;

int main(void)
{
    float f, c;

    cout << "=== CONVERSOR DE TEMPERATURA ===" << endl;
    cout << "Informe a temperatura em graus Celsius: "; cin >> c;
    cin.ignore(80, '\n');
    cout << endl;

    f = c * 9 / 5 + 32;

    cout << "Temperatura em graus Fahrenheit: " << f << endl;

    cout << endl;
    cout << "Tecle <Enter> para encerrar...";
    cin.get();

    return 0;

}
